apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-night-ingress
  namespace: default
  labels:
    app: movie-night
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: movies.erix-homelab.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: movie-night
            port:
              number: 3000
  tls:
  - hosts:
    - movies.erix-homelab.site
    secretName: movie-night-tls
