---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: movie-night-secrets
  namespace: default
spec:
  encryptedData:
    tmdb-api-key: AgA8us9P0JWD7XTWinVjtRD14s46Wo6Fh+/1PBlRW67D7ypCmXrZhwDloYxffrVA/Mio2vELn8YEoVkp6vcqD/hLqX5OgeZSHsaFQxMk+5VTLuSIqNoNp9ncDt2Sw7b36lto8DpMEgtIsO4ErPMjx1Sl26zm5IL6khzzSLJ6rAMNSdFDKmS/Sr18vcvi2zLq/lnSwSOECBg3GNoqn7ddN34rYDj7wnviJiP8VrNw/GE8DdZBqBMQk0FV6LcJAcTK5Rl5z8DgqIgFi5nLG25YZvcvxi0RT6xUK3OKpPT+Kvh3AZz57Ut0Ljtg2ld3zfq90Zskwo/moI9cvrzgWGCdwkNqlTCERhDUP02l5wrScmWg73ExUYu2RTHzwgtETTWq2wsb8NLvidqqUv025yuVHUWLeJ18z7o4GZQwXCqY3UCAHQtY9uE9l0ctnW0MPozryrCvrwtO2+Tsmm+1x0ih+K26OkF5uH8k4A3saoJojcSO3ku3tHJHVBmotrDvN7ye7wYRkpyJKL4NSM7YCtEqvXc8BOz8R2CgWW14UEILSee/S8VxN6FrGFdXWa9YvDOaR2o92gFDgtgswDDVYddD+CerLLWMfRumOUb6HYEDDXAoOdg6VB14H3I8wsXw8TquUjVcIfK6zvJ7LAR3DGqGO6kte9vJdOmP8Lf6Jc7LtPX+0lbBnRv3alOmaLOzAwWFxTUYLwA4B1mbApJvkU9DFodZodZvsk44SbU66U4qGvRs2Q==
  template:
    metadata:
      creationTimestamp: null
      name: movie-night-secrets
      namespace: default
