apiVersion: v1
kind: Service
metadata:
  name: movie-night
  namespace: default
  labels:
    app: movie-night
spec:
  type: ClusterIP
  selector:
    app: movie-night
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
